#!/usr/bin/env bash
set -euo pipefail

mkdir -p reports

python_files=$(find app -type f -name '*.py' | wc -l | tr -d ' ')
yaml_files=$(find kubernetes monitoring .github -type f \( -name '*.yml' -o -name '*.yaml' \) 2>/dev/null | wc -l | tr -d ' ')
tf_files=$(find terraform -type f -name '*.tf' | wc -l | tr -d ' ')
docker_files=$(find . -maxdepth 2 -type f \( -name 'Dockerfile' -o -name 'docker-compose.yml' \) | wc -l | tr -d ' ')

cat > reports/latest.md <<EOF
# Automated Repository Health Report

This file is generated by GitHub Actions.

| Check | Value |
|---|---:|
| Python files | ${python_files} |
| YAML files | ${yaml_files} |
| Terraform files | ${tf_files} |
| Docker-related files | ${docker_files} |

## Validation

- Python syntax: checked in CI
- Docker build: checked in CI
- Terraform formatting: checked in CI
- Kubernetes manifests: stored in \`kubernetes/\`

This report represents automated repository checks, not manual development activity.
EOF
